# Gunakan image Nginx sebagai base image
FROM nginx

# Salin file konfigurasi custom ke dalam container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 8081, 8082, dan 8083
EXPOSE 8081
EXPOSE 8082
EXPOSE 8083
